name: Daily Talabat Scraper

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:     # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Update geckodriver
        run: |
          sudo rm -f /usr/bin/geckodriver
          wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.36.0-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/bin/
          geckodriver --version

      - name: Fix PhantomJS Issue
        run: |
          npm uninstall phantomjs-prebuilt || true
          npm install phantomjs-prebuilt@2.1.13 || true
          npm cache clear --force
          npm install || true

      - name: Restore cached progress
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: current_progress.json
          key: talabat-scraper-progress-${{ github.run_id }}
          restore-keys: |
            talabat-scraper-progress-

      - name: Run Talabat scraper
        run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit progress updates
        if: always()  # Run even if previous steps fail/cancel
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add current_progress.json scraped_progress.json output/
          git commit -m "Update scraper progress and data for run ${{ github.run_id }}" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save progress to cache
        if: always()  # Run even if previous steps fail/cancel
        uses: actions/cache/save@v4
        with:
          path: current_progress.json
          key: talabat-scraper-progress-${{ github.run_id }}

      - name: Upload progress artifacts
        if: always()  # Run even if cancelled
        uses: actions/upload-artifact@v4
        with:
          name: talabat-progress-files
          path: |
            current_progress.json
            scraped_progress.json
          retention-days: 7

      - name: Cleanup
        if: always()
        run: |
          rm -rf node_modules
          rm -rf ~/.cache/ms-playwright
          
